# .github/workflows/auto-close-issue.yml
name: Auto Close Issue
on:
  issues:
    types:
      - opened
      - edited
  schedule:
    - cron: '30 1 * * *'
jobs:
  check-issue-template:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body || '';
            const required = ["复现步骤", "的版本", "必现"];
            if (required.every(str => issueBody.includes(str))) {
              return;
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "This issue is automatically closed because it does not contain all the required sections. Please edit the issue to include them and reopen it."
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
  close-inactive:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 60
          days-before-close: 0
          stale-issue-message: 'This issue was closed because it has been inactive for 60 days.'
          close-issue-reason: not_planned